name: fichaje_app_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.5
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  smooth_page_indicator: ^1.1.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

